### ISSUE TITLE
Better support Go programming language

### ISSUE THREAD

**Issue by g7r** [OlyaB/CyanTheme#1] opened 2019-03-19 17:12 UTC
I miss better highlighting for Go method receivers, function names, local variables and types.

**Comment by OlyaB** [comment] 2019-03-22 13:31
Hello! Thanks for your feedback. This problem with highlighting comes from the default light theme https://youtrack.jetbrains.com/issue/GO-1436. I'd prefer if the default light scheme was fixed instead of fixing locally for this plugin (the fixes would be inherited to this plugin automatically).

In the meantime, you can modify the editor color scheme to your liking in the Settings dialog (Preferences on macOS) — see settings in _Editor | Color Scheme | Go_.

**Closed** 2019-03-22 13:32 UTC

**Comment by cata0309** [comment] 2019-07-01 19:10
Is the issue solved ?

**Comment by OlyaB** [comment] 2019-07-08 09:58
The issue is solved for GoLand https://youtrack.jetbrains.com/issue/GO-1436. You can see the fix in v2019.2 EAP.
